/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: klrxyz (https://sketchfab.com/klrxyz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylish-white-vertebrate-toy-pink-snouted-mamma-ae562549d778449193c80d9774163f4f
Title: "Stylish White Vertebrate Toy Pink Snouted Mamma
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF,useAnimations } from '@react-three/drei'

import scene from '../assets/3d/fox.glb'

  const Mamma= ({currentAnimation, ...props})=> {
  const group = useRef();
  const { nodes, materials,animations } = useGLTF(scene);
  const {actions}=useAnimations(animations,group);
  useEffect(()=>{
        console.log(actions)
        Object.values(actions).forEach((action)=>action.stop());
        if(actions[currentAnimation]){
            actions[currentAnimation].play()
        }
        if (actions[currentAnimation]) {
          console.log(`Playing animation: ${currentAnimation}`);
          actions[currentAnimation].play();
        } else {
          console.log(`Animation ${currentAnimation} not found`);
        }
      
  },[actions,currentAnimation])
  return (
    <group ref={group} {...props} dispose={null}>
    <group name='Sketchfab_Scene'>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh
        name='Object_7'
        geometry={nodes.Object_7.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.Object_7.skeleton}
      />
      <skinnedMesh
        name='Object_8'
        geometry={nodes.Object_8.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.Object_8.skeleton}
      />
      <skinnedMesh
        name='Object_9'
        geometry={nodes.Object_9.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.Object_9.skeleton}
      />
      <skinnedMesh
        name='Object_10'
        geometry={nodes.Object_10.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.Object_10.skeleton}
      />
      <skinnedMesh
        name='Object_11'
        geometry={nodes.Object_11.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.Object_11.skeleton}
      />
    </group>
  </group>
        
  )
}

export default Mamma
